fix: suppress -Wunused-result on std::future::get() in TaskQueue
Newer Clang (shipped with macOS 27 / Xcode 26) marks std::future::get()
as [[nodiscard]], causing -Werror builds to fail:

  TaskQueue.h:52:9: error: ignoring return value of function
  declared with 'nodiscard' attribute [-Werror,-Wunused-result]

Explicitly cast to (void) to acknowledge the discarded return value.